### ISSUE TITLE
Not working with JRuby

### ISSUE THREAD

**Issue by boris-petrov** [jnormington/dotdiff#15]
`JRuby` doesn't support `rmagick` (read [here](https://github.com/jruby/jruby/wiki/C-Extension-Alternatives)) but it does offer alternatives: [RMagick4J](https://github.com/Serabe/RMagick4J). I guess it shouldn't be too hard to check the runtime and require only the gem for the specific platform. Can you do that?

**Comment by jnormington** [comment]
Hey @boris-petrov I don't know much of JRuby.

But I think we would be able to do the check you suggest by using 
`RUBY_PLATFORM == 'java'` to check if we are running within JRuby. The only concern I have is if the RMagick4J has the same methods as rmagick.

We use it for the cropping and comparing below
https://github.com/jnormington/dotdiff/blob/master/lib/dotdiff/comparer.rb https://github.com/jnormington/dotdiff/blob/master/lib/dotdiff/image/cropper.rb

I would happily accept a PR which supports this with passing specs pass with JRuby, as I'm not too sure I will get round to supporting it for about a month.
