### ISSUE TITLE
config.pixel_threshold cannot be set as percentage 

### ISSUE THREAD

**Issue by reydavidww** [jnormington/dotdiff#23]
Main downside of not being able to set percentage instead of pixels for difference threshold is an issue I am having with current Visual Regression (VR) tests I have.

Example:
I am VR testing a button with 3000 pixels total >> test failed because ~600 pixels difference.
I was going to increase the threshold as button is okay to pass with this difference but new threshold will not make sense to baseline images with higher pixels such as one that I have that has 400000 where test fail because of ~52000 difference. Increasing this threshold will make the button VR test pass all the time which won't be correct.

**Comment by jnormington** [comment]
Thanks @reydavidww for using and submitting an improvement. 
I'll have a little look at supporting percentage diff, along side the pixel value threshold

**Comment by jnormington** [comment]
Hi @reydavidww, 

I've made several updates to dotdiff, including support percent threshold config, and released version 3.0.0 of dotdiff to support this. Please install and let me know your thoughts.

**Comment by reydavidww** [comment]
Thanks @jnormington  - will start updating my set up to use percentage now.

**Comment by reydavidww** [comment]
Following up on this @jnormington. It seems to be working fine now using the percentage fix. Anyways, there's one issue on my end. Whenever, I get this error for example: `expected Capybara::Session to match image but failed with: Images are not the same dimensions to be compared Base file: 3840x2160 New file: 1920x1080`. The {file_name}.new.png no longer gets created. Main issue on my end that I run my automation on server slaves using another OS/screen resolution. Therefore, Iam not able to run the test there for first time. What I do is run the test on my local (w/ my resolution). Then execute it in the servers to get the {file_name}.new.png to then add it to my repo.

**Comment by jnormington** [comment]
Hey @reydavidww,

Yes you're right we don't move the snapshot image to new image position, when resolutions are mismatched, will have a look at some point to make this consistent. It was an oversight on my part.

**Comment by jnormington** [comment]
Hey @reydavidww

That should be fixed now. Released as version 3.0.1

**Comment by reydavidww** [comment]
Thank you - working good @jnormington..
